"""Run semantic activity analysis for all tracked identities."""

from __future__ import annotations

import argparse
import asyncio
import os
import time
from pathlib import Path

from dotenv import load_dotenv

from warehouseeye.gpu import VLLMClient, VisionAnalyzer


def _format_duration(seconds: float) -> str:
    total = max(0, int(seconds))
    hours, rem = divmod(total, 3600)
    minutes, secs = divmod(rem, 60)
    return f"{hours:02d}:{minutes:02d}:{secs:02d}"


def main() -> None:
    parser = argparse.ArgumentParser(description="Run semantic analysis over stored track crops.")
    parser.add_argument(
        "--db",
        default="data/warehouseeye.sqlite3",
        help="Path to SQLite database generated by the local pipeline.",
    )
    parser.add_argument(
        "--base-dir",
        default=".",
        help="Base directory for resolving relative crop paths.",
    )
    parser.add_argument(
        "--profile",
        choices=["dev", "prod"],
        default="dev",
        help="Select AMD_MODEL_DEV or AMD_MODEL_PROD.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Run analysis without writing activity_json back to SQLite.",
    )
    parser.add_argument(
        "--prompt-path",
        default=None,
        help="Override prompt path (defaults to prompts/activity_extraction.txt).",
    )
    parser.add_argument(
        "--strict-prompt-path",
        default=None,
        help="Override strict prompt path (defaults to prompts/activity_extraction_strict.txt).",
    )
    args = parser.parse_args()

    load_dotenv()
    os.environ["AMD_PROFILE"] = args.profile

    db_path = Path(args.db)
    if not db_path.exists():
        raise FileNotFoundError(f"Database not found: {db_path}")

    client = VLLMClient(profile=args.profile)
    analyzer = VisionAnalyzer(
        vllm_client=client,
        prompt_path=args.prompt_path,
        strict_prompt_path=args.strict_prompt_path,
        base_dir=args.base_dir,
    )

    track_durations: list[float] = []
    started_at = time.perf_counter()

    def on_track_complete(event: dict[str, object]) -> None:
        elapsed_sec = float(event["elapsed_sec"])
        index = int(event["index"])
        total_tracks = int(event["total_tracks"])
        track_id = int(event["track_id"])
        status = str(event["status"])
        processed_crops = int(event["processed_crops"])

        track_durations.append(elapsed_sec)
        avg_track_sec = sum(track_durations) / len(track_durations)
        remaining_tracks = max(0, total_tracks - index)
        eta_sec = avg_track_sec * remaining_tracks
        print(
            f"[{index}/{total_tracks}] track_id={track_id} status={status} crops={processed_crops} "
            f"track_time={elapsed_sec:.2f}s eta={_format_duration(eta_sec)}"
        )

    async def run_analysis() -> dict[str, object]:
        """Run async work in a single event loop (required for httpx AsyncClient cleanup)."""
        try:
            return await analyzer.analyze_all_tracks_async(
                db_path=db_path,
                dry_run=args.dry_run,
                on_track_complete=on_track_complete,
            )
        finally:
            await client.aclose()

    summary = asyncio.run(run_analysis())

    total_elapsed_sec = time.perf_counter() - started_at
    parse_successes = int(summary.get("parse_successes", 0))
    parse_failures = int(summary.get("parse_failures", 0))
    parse_total = parse_successes + parse_failures
    parse_success_rate = (parse_successes / parse_total * 100) if parse_total else 0.0
    avg_latency_ms = float(summary.get("average_latency_ms", 0.0))
    request_count = int(summary.get("request_count", 0))

    estimated_cost_usd = (total_elapsed_sec / 3600) * 1.99

    print("")
    print("Semantic analysis completed.")
    print(f"Tracks discovered: {int(summary.get('total_tracks', 0))}")
    print(f"Tracks analyzed: {int(summary.get('analyzed_tracks', 0))}")
    print(f"Crops analyzed: {int(summary.get('total_crops', 0))}")
    print(f"Total requests: {request_count}")
    print(f"JSON parse success rate: {parse_success_rate:.2f}% ({parse_successes}/{parse_total})")
    print(f"Average request latency: {avg_latency_ms:.2f} ms")
    print(f"Wall-clock runtime: {_format_duration(total_elapsed_sec)}")
    print(f"Estimated instance cost (@$1.99/hour): ${estimated_cost_usd:.4f}")


if __name__ == "__main__":
    main()
